# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/prism"
  version "0.6.3"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.3/prism_0.6.3_darwin_x86_64.tar.gz"
      sha256 "ec015ed28ec5851de177c43b1b4052b8ca8e9cc33161303243ed1f7957086123"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.3/prism_0.6.3_darwin_arm64.tar.gz"
      sha256 "16d8e27ef8902f6a8257d76e3ed1ee4c7c110612c906e3cdbe54dd8076923f67"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.3/prism_0.6.3_linux_x86_64.tar.gz"
      sha256 "62e8c29d19e7615a55b44400e36201f457dfd4cb4d577459289239518cc957ef"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.3/prism_0.6.3_linux_arm64.tar.gz"
      sha256 "8bee3ec59c1d6d1fc2112abe9e348049df257c1590128998b0bc83b92c3ff2ef"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      Prism has been installed!

      Command Line Interface (CLI):
        prism --help

      Terminal User Interface (TUI):
        prism tui

      Quick start:
        prism templates                           # List available templates
        prism launch <template-name> <instance>   # Launch a workstation

      The daemon (prismd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/prism
    EOS
  end

  test do
    system "#{bin}/prism", "--version"
    system "#{bin}/prismd", "--version"
  end
end
