# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/prism"
  version "0.6.0"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.0/prism_0.6.0_darwin_x86_64.tar.gz"
      sha256 "ec95688155f2b673f4d07ab7c585b02fc25db39bfafe4b90b09ce6a418981c4a"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.0/prism_0.6.0_darwin_arm64.tar.gz"
      sha256 "2ebba77f2d26f039f761aafa5275d4ee9dd7ace74d3935cef029ef645a80fcef"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.0/prism_0.6.0_linux_x86_64.tar.gz"
      sha256 "d05d90555a96d6c11e52475f59a0d057d66b7dc332c2902436a42bd369b709e0"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.6.0/prism_0.6.0_linux_arm64.tar.gz"
      sha256 "9f3cc01611a28979d445baf2027b6e8b0cc0c5fed2dfe873dc776457b9b9e580"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      Prism has been installed!

      Command Line Interface (CLI):
        prism --help

      Terminal User Interface (TUI):
        prism tui

      Quick start:
        prism templates                           # List available templates
        prism launch <template-name> <instance>   # Launch a workstation

      The daemon (prismd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/prism
    EOS
  end

  test do
    system "#{bin}/prism", "--version"
    system "#{bin}/prismd", "--version"
  end
end
