# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsRoleExec < Formula
  desc "Assume an AWS IAM role and exec a command with the credentials — sudo for AWS roles"
  homepage "https://github.com/scttfrdmn/aws-role-exec"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-role-exec/releases/download/v0.1.5/aws-role-exec_0.1.5_darwin_amd64.tar.gz"
      sha256 "12d7f6d1137eb73ba634c91fceb655a80d956450981ba4f775c26dc199b971b6"

      define_method(:install) do
        bin.install "aws-role-exec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-role-exec/releases/download/v0.1.5/aws-role-exec_0.1.5_darwin_arm64.tar.gz"
      sha256 "9184dc48bdc61e0df8a4177f4de0ad003590c74e0cb89c2382b770af12b76a6f"

      define_method(:install) do
        bin.install "aws-role-exec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-role-exec/releases/download/v0.1.5/aws-role-exec_0.1.5_linux_amd64.tar.gz"
      sha256 "5fa49b79d815833e428ade5a12892d1f8d93e78463c1396738c628c6b8509b92"
      define_method(:install) do
        bin.install "aws-role-exec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-role-exec/releases/download/v0.1.5/aws-role-exec_0.1.5_linux_arm64.tar.gz"
      sha256 "e4e7e20ddede191be2f731c3baf32c36961309d5834f94f00b53813cbecb91b4"
      define_method(:install) do
        bin.install "aws-role-exec"
      end
    end
  end

  test do
    system "#{bin}/aws-role-exec", "--version"
  end
end
