# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calque < Formula
  desc "Run Modal-shaped code on AWS, unchanged"
  homepage "https://github.com/spore-host/calque"
  version "0.6.0"
  license "Apache-2.0"

  depends_on "uv" => :runtime

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spore-host/calque/releases/download/v0.6.0/calque_0.6.0_darwin_amd64.tar.gz"
      sha256 "7f7b2f280c9230b9b9cb65a3e7232bc1018b0709d9be681ff7fa5fb072b58b76"

      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spore-host/calque/releases/download/v0.6.0/calque_0.6.0_darwin_arm64.tar.gz"
      sha256 "b512575e533886506b7920d13bce48f36928e0ff235b041ebe166ace7b5ff2f8"

      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/calque/releases/download/v0.6.0/calque_0.6.0_linux_amd64.tar.gz"
      sha256 "722113202a59bb62c13eb4d3c278ee58a2a77e993ebbcd83b5d619786c47b9e1"
      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/calque/releases/download/v0.6.0/calque_0.6.0_linux_arm64.tar.gz"
      sha256 "29f3e2dc68691de93c9bc1d38db327a633ae31056ebc8325489bd0dba1a3fc4a"
      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
  end

  test do
    system "#{bin}/calque", "version"
  end
end
