# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calque < Formula
  desc "Run Modal-shaped code on AWS, unchanged"
  homepage "https://github.com/spore-host/calque"
  version "0.5.0"
  license "Apache-2.0"

  depends_on "uv" => :runtime

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spore-host/calque/releases/download/v0.5.0/calque_0.5.0_darwin_amd64.tar.gz"
      sha256 "d412c37260abcffe09f1027e66f4912e18766d2271adfeeb08b01e71d2b544f8"

      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spore-host/calque/releases/download/v0.5.0/calque_0.5.0_darwin_arm64.tar.gz"
      sha256 "7b6a96934ae8c550adb0a478c51998c37d38ac0fff4f219a263cfd1f04bc469b"

      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/calque/releases/download/v0.5.0/calque_0.5.0_linux_amd64.tar.gz"
      sha256 "9ebd04cb5264d95da386466ae83ebea8c4047140619cdf34524822a836258729"
      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/calque/releases/download/v0.5.0/calque_0.5.0_linux_arm64.tar.gz"
      sha256 "83c5a55dd5177505f78a592032456f464120e3a517edb42637765a2427242585"
      define_method(:install) do
        libexec.install "pyast"
        (bin/"calque").write <<~SH
          #!/bin/bash
          export CALQUE_PYAST_DIR="#{libexec}/pyast"
          exec "#{libexec}/calque-bin" "$@"
        SH
        chmod 0755, bin/"calque"
        libexec.install "calque" => "calque-bin"
      end
    end
  end

  test do
    system "#{bin}/calque", "version"
  end
end
