# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cargoship < Formula
  desc "High-performance S3 upload tool with intelligent sharding and compression"
  homepage "https://github.com/scttfrdmn/cargoship"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.9.0/cargoship_0.9.0_darwin_x86_64.tar.gz"
      sha256 "2796755b3185401545321ff948108ee5e4a649ecb34e844f507e06feb4d2a244"

      def install
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.9.0/cargoship_0.9.0_darwin_arm64.tar.gz"
      sha256 "a61d823cafd526f79d59a7000840c773ed012f6058440f3fb10520ff02717f2a"

      def install
        bin.install "cargoship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.9.0/cargoship_0.9.0_linux_x86_64.tar.gz"
      sha256 "0923ae8b9d7b89ba2277ac965ec1325b3ddcc7d32adcea188b853273861277d6"
      def install
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.9.0/cargoship_0.9.0_linux_arm64.tar.gz"
      sha256 "f7b54a9bbdae0ac54d5b310be05417d6f41dc883b456f0bb81e1ea52cd90192b"
      def install
        bin.install "cargoship"
      end
    end
  end

  test do
    system "#{bin}/cargoship", "--version"
  end
end
