# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cargoship < Formula
  desc "High-performance S3 upload tool with intelligent sharding and compression"
  homepage "https://github.com/scttfrdmn/cargoship"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.6.2/cargoship_0.6.2_darwin_x86_64.tar.gz"
      sha256 "ee5c7c4dbe142f2b90217c365d6b9d242126d35f68341ad075dd23a6c49b2c74"

      def install
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.6.2/cargoship_0.6.2_darwin_arm64.tar.gz"
      sha256 "f6765c19116b1cca99bbe3780f983074bfe6e36612357147674cacafe0dd371a"

      def install
        bin.install "cargoship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.6.2/cargoship_0.6.2_linux_x86_64.tar.gz"
      sha256 "91a567960d6228f71102edf1d6f868618a8f36762c9feccc1de69fb775dccecb"
      def install
        bin.install "cargoship"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cargoship/releases/download/v0.6.2/cargoship_0.6.2_linux_arm64.tar.gz"
      sha256 "062c35c60fe2be9116f6ef06ce6c37f3d3a3bce2524d189f0532ebbe204bb547"
      def install
        bin.install "cargoship"
      end
    end
  end

  test do
    system "#{bin}/cargoship", "--version"
  end
end
