# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spawn < Formula
  desc "Launch ephemeral AWS EC2 instances effortlessly"
  homepage "https://github.com/spore-host/spawn"
  version "0.93.1"
  license "Apache-2.0"

  depends_on "spore-host/tap/truffle" => :runtime

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spore-host/spawn/releases/download/v0.93.1/spawn_0.93.1_darwin_amd64.tar.gz"
      sha256 "443ce8df6d75c0461c878b1db96cc19ca86d9e328e73c1b108410c46e4aa659e"

      define_method(:install) do
        bin.install "spawn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spore-host/spawn/releases/download/v0.93.1/spawn_0.93.1_darwin_arm64.tar.gz"
      sha256 "762b2a88171030e6b9b1d0a6c5c1e66afbb2ed4485bb02ebb2db44dd6c1af12d"

      define_method(:install) do
        bin.install "spawn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spawn/releases/download/v0.93.1/spawn_0.93.1_linux_amd64.tar.gz"
      sha256 "813f1ccda850f1f5ab7e133b6a4afa3e29276e554b85a3f1a5ce337d58b0bcd2"
      define_method(:install) do
        bin.install "spawn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spawn/releases/download/v0.93.1/spawn_0.93.1_linux_arm64.tar.gz"
      sha256 "e1e6f400bd89e5007172c722bddb87f28da75bec41bc260a996741e4f5cf1f3b"
      define_method(:install) do
        bin.install "spawn"
      end
    end
  end

  test do
    system "#{bin}/spawn", "version"
  end
end
