# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spawn < Formula
  desc "Launch ephemeral AWS EC2 instances effortlessly"
  homepage "https://github.com/spore-host/spawn"
  version "0.127.0"
  license "Apache-2.0"

  depends_on "spore-host/tap/truffle" => :runtime

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spore-host/spawn/releases/download/v0.127.0/spawn_0.127.0_darwin_amd64.tar.gz"
      sha256 "e8312527c00f0b2091b7e118a6d9be72a03c5af3624259279f2f9c872fcde45d"

      define_method(:install) do
        bin.install "spawn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spore-host/spawn/releases/download/v0.127.0/spawn_0.127.0_darwin_arm64.tar.gz"
      sha256 "4834b4028b5222afc9a0f348e7c96b8144567e870428e1a5dbd0129a0e6d825a"

      define_method(:install) do
        bin.install "spawn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spawn/releases/download/v0.127.0/spawn_0.127.0_linux_amd64.tar.gz"
      sha256 "e88d9e45710376f7a40fd564baaa7c8bc0ed3601f8d799cb0322fa0765112df1"
      define_method(:install) do
        bin.install "spawn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spawn/releases/download/v0.127.0/spawn_0.127.0_linux_arm64.tar.gz"
      sha256 "f257b6d1ccbedec9e3ea65a3a757ccf28d3b82868c50a2adcb3245f05228800a"
      define_method(:install) do
        bin.install "spawn"
      end
    end
  end

  test do
    system "#{bin}/spawn", "version"
  end
end
