# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SporeHostMcp < Formula
  desc "MCP server for AI assistants — manage EC2 instances and discover capacity"
  homepage "https://github.com/spore-host/spore-host"
  version "0.34.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.5/spore-host-mcp_0.34.5_darwin_amd64.tar.gz"
      sha256 "40c354ad4aca6477d7b94f894bdee6cfbfae6d50980f7e71f8c927abb9937146"

      define_method(:install) do
        bin.install "spore-host-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.5/spore-host-mcp_0.34.5_darwin_arm64.tar.gz"
      sha256 "ef3d7e527e7c0e95e56cee97cb01105d396f6f3a19c6f10b542ffbc2fee64792"

      define_method(:install) do
        bin.install "spore-host-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.5/spore-host-mcp_0.34.5_linux_amd64.tar.gz"
      sha256 "9f1e90ef2186883599d152f3bb6465a107ed5a1833776f21d30bd0900e1ea44e"
      define_method(:install) do
        bin.install "spore-host-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.5/spore-host-mcp_0.34.5_linux_arm64.tar.gz"
      sha256 "2215f52fe053dfddf8bc2f95fcdb8026ebbdfafde8893ea93a2e1b1cf967da94"
      define_method(:install) do
        bin.install "spore-host-mcp"
      end
    end
  end
end
