# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Truffle < Formula
  desc "Find and discover AWS EC2 instance types"
  homepage "https://github.com/spore-host/spore-host"
  version "0.34.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.8/truffle_0.34.8_darwin_amd64.tar.gz"
      sha256 "b2d710d1e848dcb1e1c96b82125cc098e3b3e133f4e3b60ae4ea6c23a9666c35"

      define_method(:install) do
        bin.install "truffle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.8/truffle_0.34.8_darwin_arm64.tar.gz"
      sha256 "7c642282f00caa2f4ebf55e44988363f31acfed3baa1f224ffebdd3b163138d1"

      define_method(:install) do
        bin.install "truffle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.8/truffle_0.34.8_linux_amd64.tar.gz"
      sha256 "099c9aed81b78f5da1b2332a90fd403417a96d0c31d1908ef2864eed2c93837b"
      define_method(:install) do
        bin.install "truffle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spore-host/spore-host/releases/download/v0.34.8/truffle_0.34.8_linux_arm64.tar.gz"
      sha256 "958fcf556c1e968b484f5122352275b97928419fe5376a3f3c279bd60bdd5663"
      define_method(:install) do
        bin.install "truffle"
      end
    end
  end

  test do
    system "#{bin}/truffle", "version"
  end
end
