# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Truffle < Formula
  desc "Find and discover AWS EC2 instance types"
  homepage "https://github.com/scttfrdmn/spore-host"
  version "0.29.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/spore-host/releases/download/v0.29.1/truffle_0.29.1_darwin_amd64.tar.gz"
      sha256 "24719c40f9442e2e62c77c65e57bd5a9a41c46e08c1160f4b798d8f5a34f29b6"

      define_method(:install) do
        bin.install "truffle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/spore-host/releases/download/v0.29.1/truffle_0.29.1_darwin_arm64.tar.gz"
      sha256 "ca0fe0fa6c719e78c32c98c1ea7d5d236f71c0519d4c79d291a71a10ce6c1f56"

      define_method(:install) do
        bin.install "truffle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/spore-host/releases/download/v0.29.1/truffle_0.29.1_linux_amd64.tar.gz"
      sha256 "be02c4126749b96af9c1828dc69a9f88000878e13b6fca7b80712d1748dbc1d1"
      define_method(:install) do
        bin.install "truffle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/spore-host/releases/download/v0.29.1/truffle_0.29.1_linux_arm64.tar.gz"
      sha256 "61603eb172fdac12cdd14f0ff1e7d931539ebd00bd7b092925760ac2c578a6d1"
      define_method(:install) do
        bin.install "truffle"
      end
    end
  end

  test do
    system "#{bin}/truffle", "version"
  end
end
